apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fuego-cloud

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - secret.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: fuego-cloud
