apiVersion: v1
kind: Service
metadata:
  name: nexo-cloud
  labels:
    app.kubernetes.io/name: nexo-cloud
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: nexo-cloud
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP
