---
k3s_version: "v1.31.3+k3s1"
k3s_token: "{{ lookup('env', 'K3S_TOKEN') | default('fuego-cluster-token', true) }}"
k3s_cluster_cidr: "10.42.0.0/16"
k3s_service_cidr: "10.43.0.0/16"
k3s_disable_traefik: true
k3s_disable_servicelb: true
